minVersion: "1.8.1"
github:
  owner: getsentry
  repo: pdb
changelogPolicy: auto

statusProvider:
  name: github
artifactProvider:
  name: none

preReleaseCommand: bash scripts/bump-version.sh
targets:
  - name: github
  - name: crates
