language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  include:
    - name: rustfmt
      install: rustup component add rustfmt
      script: cargo fmt -- --check
    - name: clippy
      install: rustup component add clippy
      script: cargo clippy --all-features --tests --all --examples -- -D clippy::all
  allow_failures:
    - rust: nightly
script:
  - wget https://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/3844dbb920174967be7aa4a2c20430fa2/ntkrnlmp.pdb -O fixtures/symbol_server/ntkrnlmp.pdb
  - cargo build --verbose --all
  - cargo test --verbose --all
